[package]
name = "plugin-example"
version = "0.1.0"
authors = ["mexus <gilaldpellaeon@gmail.com>"]
publish = false

[dependencies]
plugin-mgmt = { path = "../plugin-mgmt/" }

[lib]
crate-type = ["cdylib"]
